### ISSUE TITLE
Basic utility classes

### ISSUE THREAD

**Issue by janperse** [orangeui/orange#34]
- [x] Border radius class - 3px is our standard
- [x] Margin center (`margin: 0 auto;`)
- [x] `.hidden` for `display: none;`
- [x] Display classes (`inline, block, flex, potentially switching hidden with none)
- [x] Text styles (`underline, etc.`)
- [x] Flex classes (`flex, flex positioning`)

**Comment by ryanckulp** [comment]
* something for `margin: 0 auto;`
* `hidden` -> `display: none;` 
* display-inline
* display-block
* text-underline

**Comment by janperse** [comment]
@ryanckulp updated the description with your ideas, thanks!
